name: Common Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2
        with:
          powershell-version: "5.1"

      - name: Install Pester
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run Tests
        run: |
          Invoke-Pester -Path tests -Output Detailed
